// frontend/pages/index.vue
<template>
  <div>
    <div>TOP</div>
    <div v-if="response.themes.length > 0">
    <table>
      <tr>
        <th>NAME</th>
        <th>DETAIL</th>
      </tr>
      <tr v-for="theme in response.themes" :key="theme.ID">
        <nuxt-link :to="`/themes/${theme.ID}`"><td>{{ theme.Name }}</td></nuxt-link>
        <td>{{ theme.Detail }}</td>
      </tr>
    </table>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import axios from 'axios'

type Theme = {
  ID: number
	CreatedAt: string
	UpdatedAt: string
  DeletedAt: string

  Name: string
  Detail: string
  Comments: Comment[]
}
type Comment = {
  ID: number
	CreatedAt: string
	UpdatedAt: string
  DeletedAt: string

  Body: string
  ThemeId: number
}

export default Vue.extend({
  data() {
    return {
      response: {themes: []},
    }
  },
  mounted() {
    axios.get('http://localhost:8080/service/v0/themes')
      .then((response) => {
        this.response = response.data
      })
  }
})
</script>

// frontend/pages/index.tsx
import { GetServerSideProps } from "next"
import Link from "next/link"

const BACKEND_API_THEMES_BASE_PATH = "http://localhost:8080/service/v1/themes"

type Theme = {
    id: number
    name: string
    detail: string
}

export default function Home({
  indexData
}: {
  indexData : Theme[]
}) {
  return (
    <div>
      <h1>Theme</h1>
      <div>
        <ul>
          {indexData.map(data => {
            return (
              <li>
                <Link href={`/themes/${data.id}`}>
                  <a>{data.name}</a>
                </Link>
                &nbsp;{data.detail}
              </li>
            )
          })}
        </ul>
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch(BACKEND_API_THEMES_BASE_PATH)
  const data = await response.json()

  console.log(data.themes)

  return {
    props: {
      indexData: data.themes
    }
  }
}
